version: '2.4'

services:
  face_recognizer:
    depends_on:
      - face_index
      - minio
    mem_limit: 16G
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    tty: true
    ports:
      - "4446:4446"
    environment:
      IS_TEST: $test
      S3_URL: $S3_URL
      S3_ACCESS_KEY: $S3_ACCESS_KEY
      S3_SECRET_KEY: $S3_SECRET_KEY
      S3_VERIFY_TLS: $S3_VERIFY_TLS
      FACE_RECOGNIZER_HOST: $FACE_RECOGNIZER_HOST
      FACE_RECOGNIZER_PORT: $FACE_RECOGNIZER_PORT
      FACE_INDEX_HOST: $FACE_INDEX_HOST
      FACE_INDEX_PORT: $FACE_INDEX_PORT

  pg:
    container_name: pg
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: face_index
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  #  pg:
#    image: postgres:9.6
#    restart: always
#
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: face_index
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 2s
#      timeout: 2s
#      retries: 10
#    ports:
#      - "5432:5432"
#    command:
#      "postgres -c max_connections=128 -c shared_buffers=4GB -c effective_cache_size=4GB -c work_mem=256MB"

  face_index:
    depends_on:
      pg:
        condition: service_healthy
    links:
      - pg
    image: "nexus.intra.ispras.ru:31334/face_index:latest"
    mem_limit: 16G
    environment:
      PYTHONUNBUFFERED: 1
      FACE_INDEX_PORT: $FACE_INDEX_PORT
      FACE_INDEX_HOST: $FACE_INDEX_HOST
      DB_URL: $DB_URL
    restart: always
    ports:
        - "4445:4445"


  test:
    depends_on:
      - pg
      - face_recognizer
      - face_index
    build:
          context: .
          dockerfile: docker/Dockerfile
    tty: true
    environment:
      FACE_INDEX_PORT: $FACE_INDEX_PORT
      FACE_INDEX_HOST: $FACE_INDEX_HOST
      FACE_RECOGNIZER_HOST: $FACE_RECOGNIZER_HOST
      FACE_RECOGNIZER_PORT: $FACE_RECOGNIZER_PORT
      IS_TEST: $test
      S3_URL: $S3_URL
      S3_ACCESS_KEY: $S3_ACCESS_KEY
      S3_SECRET_KEY: $S3_SECRET_KEY
      S3_VERIFY_TLS: $S3_VERIFY_TLS
      PYTHONPATH: $PYTHONPATH:/face_recognizer_root/tests:/face_recognizer_root
    command:
      bash -c "bash face_recognizer_root/tests/run_tests_in_docker.sh"

  minio:
    image: "minio/minio"
    hostname: minio
    container_name: face_recognizer_minio
    command: server /data
    environment:
      MINIO_ROOT_USER: $S3_ACCESS_KEY
      MINIO_ROOT_PASSWORD: $S3_SECRET_KEY
    ports:
      - "9000:9000"

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1: